// Generated by gencpp from file dk_adap_test/state.msg
// DO NOT EDIT!


#ifndef DK_ADAP_TEST_MESSAGE_STATE_H
#define DK_ADAP_TEST_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dk_adap_test
{
template <class ContainerAllocator>
struct state_
{
  typedef state_<ContainerAllocator> Type;

  state_()
    : header()
    , child_frame_id()
    , x(0.0)
    , y(0.0)
    , phi(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)  {
    }
  state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , child_frame_id(_alloc)
    , x(0.0)
    , y(0.0)
    , phi(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _child_frame_id_type;
  _child_frame_id_type child_frame_id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;





  typedef boost::shared_ptr< ::dk_adap_test::state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dk_adap_test::state_<ContainerAllocator> const> ConstPtr;

}; // struct state_

typedef ::dk_adap_test::state_<std::allocator<void> > state;

typedef boost::shared_ptr< ::dk_adap_test::state > statePtr;
typedef boost::shared_ptr< ::dk_adap_test::state const> stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dk_adap_test::state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dk_adap_test::state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dk_adap_test::state_<ContainerAllocator1> & lhs, const ::dk_adap_test::state_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.child_frame_id == rhs.child_frame_id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.phi == rhs.phi &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.angular_velocity == rhs.angular_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dk_adap_test::state_<ContainerAllocator1> & lhs, const ::dk_adap_test::state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dk_adap_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dk_adap_test::state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dk_adap_test::state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dk_adap_test::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dk_adap_test::state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dk_adap_test::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dk_adap_test::state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dk_adap_test::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "140a803ed3c5e06fc1dbfe9d2d41136d";
  }

  static const char* value(const ::dk_adap_test::state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x140a803ed3c5e06fULL;
  static const uint64_t static_value2 = 0xc1dbfe9d2d41136dULL;
};

template<class ContainerAllocator>
struct DataType< ::dk_adap_test::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dk_adap_test/state";
  }

  static const char* value(const ::dk_adap_test::state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dk_adap_test::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string child_frame_id\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 phi\n"
"float64 linear_velocity\n"
"float64 angular_velocity\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dk_adap_test::state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dk_adap_test::state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.child_frame_id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.phi);
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dk_adap_test::state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dk_adap_test::state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "child_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.child_frame_id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DK_ADAP_TEST_MESSAGE_STATE_H
