<?xml version="1.0"?>
<robot name="wheels" 
       xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="wheel" params="fb lr shaft translateY">
    <link name="wheel_${fb}_${lr}_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> 
            <geometry>
                <cylinder length="${wheel_height}" radius="${wheel_radius}" />
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> 
            <geometry>
                <cylinder length="${wheel_height}" radius="${wheel_radius}" />
            </geometry>
            <material name="Black" />
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" />
            <cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />
        </inertial>
    </link>

    <joint name="wheel_${fb}_${lr}_joint" type="fixed">
        <parent link="${shaft}_shaft_${fb}_${lr}_link" />
        <child link="wheel_${fb}_${lr}_link" />
        <origin xyz="0
                     ${translateY} 
                     0" 
                rpy="0 0 0" />
    </joint>  
  </xacro:macro>

<!-- WHEELS -->
  <wheel fb="front" lr="left" shaft="motor" translateY="${wheel_offset_from_balancer_shaft + wheel_balancer_offset_from_motor_shaft}" />
  <wheel fb="front" lr="right" shaft="motor" translateY="${-wheel_offset_from_balancer_shaft - wheel_balancer_offset_from_motor_shaft}" />
  <wheel fb="middle" lr="left" shaft="balancer" translateY="${wheel_offset_from_balancer_shaft}" />
  <wheel fb="middle" lr="right" shaft="balancer" translateY="${-wheel_offset_from_balancer_shaft}" />
  <wheel fb="back" lr="left" shaft="balancer" translateY="${wheel_offset_from_balancer_shaft}" />
  <wheel fb="back" lr="right" shaft="balancer" translateY="${-wheel_offset_from_balancer_shaft}" />

</robot>
